### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by malikdoksoz** [nerdvibe/clorio-client#38]
Can you add epoch times, refresh balance button, 2FA verification thanks for developing

epoch examle;
![C80CAF6C-10F8-4608-911A-591928D21FAB](https://user-images.githubusercontent.com/26676061/120518943-c75d4f00-c3da-11eb-81be-d417d907f4d2.jpeg)

**Comment by nerdvibe** [comment]
hi @malikdoksoz , thank you for your suggestions. They are very welcome and helps us to grow. Let me try to reply to each suggestion:

- epoch times: Yes we already have this in the works and partially developed
- refresh balance: That is also already developed a PR should be made soon (aka to be expected in the next releases)
- 2FA verification: This is something that requires a bit of thinking as the keys are not stored on the device, but we'll take it into consideration :)

**Comment by nerdvibe** [comment]
Closing because both the epoch info and the refresh balance have been added on Clorio 🙏
