### ISSUE TITLE
Clorio does't show transaction rcvd with memo

### ISSUE THREAD

**Issue by aresstokrat** [nerdvibe/clorio-client#47]
I see transaction in auro wallet and in explorer, but clorio shows wron balance becouse does't see this transaction.

https://minaexplorer.com/transaction/CkpZmXRrrut9NwjpX43LQeFS1mnkcCaQdXy7rGQWgE7qECWESowLs

**Comment by nerdvibe** [comment]
I think this was an out-of-sync node scenario. Sometimes, in particular, with Mina Protocol, nodes can go out of sync. Probably this was the case.

I will close this issue and re-open it in case the issue is something different.
