### ISSUE TITLE
Mainnet does not access github release url env variable in the popup. 

### ISSUE THREAD

**Issue by karukenert** [nerdvibe/clorio-client#67]
The devnet.clor.io environment accesses the github release env variable but the mainnet.clorio.io doesn't. 

ClorioAppBanner.tsx: 

>   <div>
          <p>
            To enhance your security we recommend to download Clorio Desktop.
          </p>
          <p>
            Download Clorio Desktop{" "}
            <a
              href={process.env.REACT_APP_GITHUB_RELEASE_URL}
              target="_blank"
              rel="noreferrer"
            >
              here.
            </a>
          </p>
 </div>

The same env variable is also used in UpdateError.tsx

**Comment by nerdvibe** [comment]
Oh yes, thank you! The issue was that the latest build of Clorio was built with the `REACT_APP_GITHUB_RELEASE_URL` variable not set.

Will be fixed on the next release. Thank you so much for the report 🙏

**Comment by nerdvibe** [comment]
resolved on the latest Clorio update, thank you for the report 🙏
