### ISSUE TITLE
GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by krims0n32** [nerdvibe/clorio-client#78]
```
○ ./Clorio-Wallet-1.0.0.AppImage
Checking for update
Update for version 1.0.0 is not available (latest version: 1.0.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[62788:0315/123657.063910:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
[1]    62788 trace trap (core dumped)  ./Clorio-Wallet-1.0.0.AppImage
```

I am running Arch Linux. The previous wallet worked fine.

**Comment by krims0n32** [comment]
Any ideas? I much prefer the desktop app over the web app.

**Comment by ovidiucs** [comment]
According to this issue https://github.com/LedgerHQ/ledger-live-desktop/issues/4253 it seems to be electron related. 
I ran with the app with `--no-sandbox` argument and it worked

**Comment by str1der420** [comment]
Same error thrown here, I'm on Fedora 37
