### ISSUE TITLE
How to restore a Browser Wallet?

### ISSUE THREAD

**Issue by erikd** [nerdvibe/clorio-client#82]
I have created a browser wallet at https://clor.io but not yet transferred any funds into it.

To test that I could get my funds back if I do transfer them in, I would like to test restoring the wallet from a seed phrase, but I can't even figure out how to do that. I get two options on the first screen "Create a wallet" or "Login", but I do not want either, I want to restore a wallet from the seed phrase. Furthermore I was never prompted to create a passphrase (ie specifically not a seed phrase) so I can't even log in.

Clues?

**Comment by nerdvibe** [comment]
In order to restore your wallet, you just need to "login" with your seed phrase :)
