### ISSUE TITLE
Clorio AppImage application does not work

### ISSUE THREAD

**Issue by erikd** [nerdvibe/clorio-client#83]
Tried using the Clorio AppImage application on Debian Testing. Running it from the command line resutls in:

```
 $ MinaWallet/Clorio-Wallet-1.0.0.AppImage 
Checking for update
Update for version 1.0.0 is not available (latest version: 1.0.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

and the main window looks like:

![clorio-appimage](https://user-images.githubusercontent.com/307277/202931665-93af3039-6133-408d-b072-06f9d66c3d42.png)

**Comment by SvenMeyer** [comment]
Just downloaded Clorio-Wallet-1.0.0.AppImage [v1.0.0](https://github.com/nerdvibe/clorio-client/tree/v1.0.0) - 27578ef

First issue, my SHA512 looks different
```
$ sha512sum Clorio-Wallet-1.0.0.AppImage 
43cfb3982c38f1715b3c69ea2c90f09a441fc383b9459f4d946ad7c93ed48de93983c2350c6b0b1b3c69fd7882c06ebc6ebd0c333e7d8ca4c16d6af9db23b095  Clorio-Wallet-1.0.0.AppImage
```

Starting the AppImage on Manjaro / Arch Linux gives the same blank screen ...

```
$ ./Clorio-Wallet-1.0.0.AppImage 
Checking for update
Update for version 1.0.0 is not available (latest version: 1.0.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null

```

**Comment by nerdvibe** [comment]
Sorry for the delayed answer, as discussed on Discord, we are aware of the AppImage issue on some distributions and we didn't prioritize yet that issue. 
Regarding the SHA512, there is a misunderstanding:

The checksum file is signed by carbonaracrypto on keybase (https://keybase.io/carbonaracrypto) and uses SHA512. (serves to prove the legitimacy of the signer) (the BEGIN PGP SIGNED MESSAGE)
The files are checksums are SHA256. (serves to prove the legitimacy of the file) (the numbers with the file name)

- To prove the legitimacy of the signer you need to put the checksum signed text here https://keybase.io/verify
- To prove the legitimacy of the file you can follow this guide: https://docs.clor.io/desktop-application/verify-authenticity-of-clorio-wallet-apps

**Comment by SvenMeyer** [comment]
I just tried to run `Clorio.Wallet-2.1.2.AppImage` on Manjaro Linux 24 and got this error message :

```
$ ./Clorio.Wallet-2.1.2.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.mount_ClorioimBU59/resources/app.asar.unpacked/node_modules/usb/build/Release/usb_bindings.node: invalid ELF header
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2358)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at load (/tmp/.mount_ClorioimBU59/resources/app.asar/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/tmp/.mount_ClorioimBU59/resources/app.asar/node_modules/usb/dist/usb/bindings.js:8:36)
libva error: /usr/lib/dri/i965_drv_video.so init failed

```

I never had any problems running any AppImage so far, so it is a bit disappointing that this is still not working and nobody cares ...

**Comment by nerdvibe** [comment]
Resolved in the previous versions, closing for now.
