### ISSUE TITLE
Clorio 2.1.2 Linux build is broken

### ISSUE THREAD

**Issue by r0tc** [nerdvibe/clorio-client#87]
The latest Clorio 2.1.2 is broken for Linux, both AppImage and .deb throw on start:
`
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.mount_Clorio9Jz4NH/resources/app.asar.unpacked/node_modules/usb/build/Release/usb_bindings.node: invalid ELF header
`

**Comment by nerdvibe** [comment]
@r0tc thank you for opening this issue. Pinging @Cryptosaka

**Comment by nerdvibe** [comment]
Resolved in the previous versions, closing for now.
