### ISSUE TITLE
Getting different shasum

### ISSUE THREAD

**Issue by Sturmkater** [nerdvibe/clorio-client#89]
shasum -a 512 clorio-wallet_2.1.2_amd64.deb 
7a90c4c5bad02f4be692d14920ea316498f68616c7e95e9dd56047096560dce3314c7c14f73f68ae3dba63b7f094e055dc8f2b17cf6d373b207e7fbf1125b863

shasum -a 512 Clorio.Wallet-2.1.2.AppImage  Di 10 Sep 2024 23:15:41
ec7281164871c2cc7ba4161815b060b7296479c0ea692770f8a1e297150726efc5e417bb24ad4672cef2c105cb81c66b9b60a776df1eb644aa5746a4aa8cd97c

**Comment by nerdvibe** [comment]
Hey @Sturmkater you should try `shasum -a 256`. Further instructions here: https://docs.clor.io/desktop-application/verify-authenticity-of-clorio-wallet-apps
